### ISSUE TITLE
문자열 "필수"가 아니라 MANDATORY가 들어가야 분류가 재대로 되는거 같습니다

### ISSUE THREAD

**Issue by tktcod** [corini-9jo/campManageApp#14]
https://github.com/corini-9jo/campManageApp/blob/d88afc6db0a04161c7b59f78b78aa1467218bb16/src/main/java/camp/ScoreManagement.java#L102-L107C6

**Comment by tktcod** [comment]
이런 단어 하나 수정하는 것도 pr 형식으로 하나요?

**Comment by hu6r1s** [comment]
수정했습니다.
